/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if _MSC_VER
#pragma pack (push,4)
#endif

#ifndef MH2_C_V17_API
#define MH2_C_V17_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern MH2_C_V17_API FName MH2_C_V18_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


class MH2_C_V17_API AMonsterBasePlus : public AMutator
{
public:
    BITFIELD bInitCheck:1 GCC_PACK(4);
    INT NumVoters GCC_PACK(4);
    class ADeathMatchPlus* MyGame;
    BITFIELD bPreInitialized:1 GCC_PACK(4);
    BITFIELD bPostInitialized:1;
    FLOAT LastMonsterAttackTime GCC_PACK(4);
    FLOAT LastMadTime;
    FLOAT LastMonsterCountTime;
    INT healthtimer;
    INT RegenAmmo;
    INT RegenHealth;
    INT HealthKillRegen;
    INT AmpCount;
    INT kakuCount;
    INT HealthCount;
    INT LevelMonster;
    INT MySkill;
    INT Ways;
    BITFIELD bMidGameVote:1 GCC_PACK(4);
    FLOAT randomoffset GCC_PACK(4);
    FLOAT randomconstant;
    INT VoteTime;
    BITFIELD UseAwards:1 GCC_PACK(4);
    FStringNoInit Username GCC_PACK(4);
    FStringNoInit ServerPassword;
    BITFIELD bVoted:1 GCC_PACK(4);
    INT FItems GCC_PACK(4);
    FLOAT md;
    BITFIELD bUseCoopTranslocator:1 GCC_PACK(4);
    BITFIELD bScaleRegen:1;
    BITFIELD bUseCrapSpree:1;
    BITFIELD bCorrodeFaster:1;
    BITFIELD bNoTranslator:1;
    BITFIELD bNoRiskCannon:1;
    INT AmpTime GCC_PACK(4);
    INT KakuTime;
    INT HealthTime;
    BITFIELD StopPlayerCollision:1 GCC_PACK(4);
    INT NumCapacity GCC_PACK(4);
    BITFIELD bRemoveBlocking:1 GCC_PACK(4);
    FLOAT MHealthMultiplier GCC_PACK(4);
    INT MaxMonsterHealth;
    INT StartingAmmoAmmount;
    BITFIELD GiveEXUWeapons:1 GCC_PACK(4);
    BITFIELD PlayerNeverAutoSwitchWeapon:1;
    BITFIELD bUseAntiboost:1;
    BITFIELD bUseWarnTeamDamage:1;
    BITFIELD bUseAltScoring:1;
    BITFIELD bHitsounds:1;
    FLOAT HitVolume GCC_PACK(4);
    INT MaxHealth;
    INT MaxRegenHealth;
    INT DefaultHealth;
    INT MaxAmmoMultiplier;
    INT AmmoRespawnTime;
    BITFIELD bUseRegenAmmo:1 GCC_PACK(4);
    BITFIELD bUseRegenHealth:1;
    INT HealthRegenPerSec GCC_PACK(4);
    INT AmmoRegenPerSec;
    BITFIELD bUseSelfDamage:1 GCC_PACK(4);
    BITFIELD bUseTeamDamage:1;
    FLOAT SelfDamageScale GCC_PACK(4);
    BITFIELD bBounceOffPlayer:1 GCC_PACK(4);
    INT MaxAmmoRegen GCC_PACK(4);
    BITFIELD bNo:1 GCC_PACK(4);
    BITFIELD DoubleJump:1;
    INT maxJumps GCC_PACK(4);
    INT jumpType;
    FLOAT jumpHeight;
    BYTE datestamp;
    INT tempindex;
    class UClass* WeaponClasses[18];
    //DECLARE_FUNCTION(execRestoreFunction);	//NO! Bad compiler! NO!
    //DECLARE_FUNCTION(execReplaceFunction);
    DECLARE_FUNCTION(execReplaceLastFunction);
    DECLARE_FUNCTION(execAddState);
    DECLARE_FUNCTION(execReplaceState);
    DECLARE_FUNCTION(execDeleteMap);
    DECLARE_FUNCTION(execCollideSphere);
	DECLARE_FUNCTION(execAllClasses);
	DECLARE_FUNCTION(execDrawLine3D);
	DECLARE_FUNCTION(execNewContext);
	DECLARE_FUNCTION(execDebugDynamicCast);
	DECLARE_FUNCTION(execDebugDefaultVariable);
	DECLARE_FUNCTION(execDebugInstanceVariable);
	DECLARE_FUNCTION(execDebugLocalVariable);
	DECLARE_FUNCTION(execDebugLet);
	DECLARE_FUNCTION(execDebugClassContext);
    DECLARE_CLASS(AMonsterBasePlus,AMutator,0|CLASS_Config,MH2_C_V18)
    NO_DEFAULT_CONSTRUCTOR(AMonsterBasePlus)
};

#endif

//AUTOGENERATE_FUNCTION(AMonsterBasePlus,3561,execRestoreFunction);
//AUTOGENERATE_FUNCTION(AMonsterBasePlus,3560,execReplaceFunction);
AUTOGENERATE_FUNCTION(AMonsterBasePlus,1961,execReplaceLastFunction);
AUTOGENERATE_FUNCTION(AMonsterBasePlus,1960,execAddState);
AUTOGENERATE_FUNCTION(AMonsterBasePlus,1959,execReplaceState);
AUTOGENERATE_FUNCTION(AMonsterBasePlus,2036,execDeleteMap);
AUTOGENERATE_FUNCTION(AMonsterBasePlus,1962,execCollideSphere);
AUTOGENERATE_FUNCTION(AMonsterBasePlus,1963, execAllClasses);
AUTOGENERATE_FUNCTION(AMonsterBasePlus,1964, execDrawLine3D);
AUTOGENERATE_FUNCTION(AMonsterBasePlus,1965, execNewContext);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif NAMES_ONLY

#if _MSC_VER
#pragma pack (pop)
#endif
